name: bookreview

server:
  port: 8080

spring:
  application:
    name: bookReviewApp

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:test
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      max-lifetime: 300000
    initialization-mode: always
    continue-on-error: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        globally_quoted_identifiers: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true